/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.88
 * Generated at: 2024-11-28 07:29:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.html;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class vattu_005fuser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar", Long.valueOf(1732605426315L));
    _jspx_dependants.put("jar:file:/C:/Users/Toanvupc/Desktop/quan_li_vat_tu/QLVT/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/quanlivattu/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar!/META-INF/c.tld", Long.valueOf(1323233178000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Vật tư và thiết bị</title>\r\n");
      out.write("    <!--css-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/vattu.css\">\r\n");
      out.write("    <!--boostrap-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bootstrap/bootstrap.min.css\">\r\n");
      out.write("    <!--icon-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/icon/font/bootstrap-icons.min.css\">\r\n");
      out.write("    <!--js bootstrap-->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bootstrap/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <!--font-->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400..700&family=Mona+Sans:ital,wght@0,200..900;1,200..900&family=Noto+Sans:ital,wght@0,100..900;1,100..900&family=Playfair+Display:ital,wght@0,400..900;1,400..900&family=Playwrite+DE+Grund:wght@100..400&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <!--datatable-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.7.0.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("    <!--xuatfile-->\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.17.0/xlsx.full.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"font-family: 'Mona Sans', serif;\">\r\n");
      out.write("    <!--sidebar-->\r\n");
      out.write("    <div id=\"sidebar\" class=\"sidebar\">\r\n");
      out.write("        <div class=\"m-3 mt-3\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"logo d-flex align-items-center\">\r\n");
      out.write("                <a class=\"nav-link fade-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/html/trangchu_user.jsp\">\r\n");
      out.write("                    <i class=\"bi bi-heart-pulse-fill\"></i>\r\n");
      out.write("                    <span class=\"ms-2\">VẬT TƯ Y TẾ</span>\r\n");
      out.write("                </a>               \r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"dashboard mt-5 ms-3\">\r\n");
      out.write("            <ul class=\"navbar-nav\">\r\n");
      out.write("                <li id=\"checked\" class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link ms-3 m-2 fade-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/html/vattu_user.jsp\">\r\n");
      out.write("                        <i class=\"bi bi-database-fill me-2\"></i>\r\n");
      out.write("                        Vật tư & thiết bị\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link ms-3 m-2 fade-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/html/yeucau_user.jsp\">\r\n");
      out.write("                        <i class=\"bi bi-hand-index-fill me-2\"></i>\r\n");
      out.write("                        Yêu cầu vật tư\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link ms-3 m-2 fade-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/html/lichsu_user.jsp\">\r\n");
      out.write("                        <i class=\"bi bi-clock-history me-2\"></i>\r\n");
      out.write("                        Lịch sử yêu cầu\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link ms-3 m-2 fade-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/html/nhan_user.jsp\">\r\n");
      out.write("                        <i class=\"bi bi-inboxes-fill me-2\"></i>\r\n");
      out.write("                        Nhận vật tư\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"log-out\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/html/dangnhap.jsp\">\r\n");
      out.write("                Đăng Xuất\r\n");
      out.write("                <i class=\"bi bi-box-arrow-right\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("       \r\n");
      out.write("    </div>\r\n");
      out.write("    <!--end sidebar-->\r\n");
      out.write("    <!--main content-->\r\n");
      out.write("    <main id=\"main-content\" class=\"main-content h-100\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"header\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row w-100\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"toggle col-1 col-sm-1\">\r\n");
      out.write("                    <button id=\"toggle\">☰</button>\r\n");
      out.write("                </div>\r\n");
      out.write("    \r\n");
      out.write("                <div class=\"search-bar col-11 col-sm-7\">\r\n");
      out.write("                    <input onkeyup=\"searchTable()\" id=\"searchInput\" type=\"text\" class=\"form-control\" placeholder=\"Tìm kiếm gì đó...\">\r\n");
      out.write("                </div>\r\n");
      out.write("    \r\n");
      out.write("                <div class=\"hello col-12 col-sm-4\">\r\n");
      out.write("                    <span id=\"hello\">Xin chào!</span>\r\n");
      out.write("                    <span id=\"name\">Nguyễn Anh Đức</span>\r\n");
      out.write("                    <span><img src=\"https://png.pngtree.com/png-vector/20220429/ourlarge/pngtree-human-template-doctor-avatar-white-individual-vector-png-image_27845716.jpg\" alt=\"\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"content-here mt-3\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"thongke row\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"mt-3 col-12 col-sm-4\">\r\n");
      out.write("                    <div class=\"thongke1\">\r\n");
      out.write("                        Tổng số vật tư\r\n");
      out.write("                        <p>\r\n");
      out.write("                            <i class=\"bi bi-basket\"></i>\r\n");
      out.write("                            <span>100</span>\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"mt-3 col-12 col-sm-4\">\r\n");
      out.write("                    <div class=\"thongke2\">\r\n");
      out.write("                        Nhà cung cấp nổi bật\r\n");
      out.write("                        <p>\r\n");
      out.write("                            <i class=\"bi bi-bus-front-fill\"></i>\r\n");
      out.write("                            <span>Nhà cung cấp A</span>\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"card\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"container mt-5\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-3\">\r\n");
      out.write("                            <ul class=\"list-group\">\r\n");
      out.write("                                <li class=\"list-group-item\" id=\"sort-asc\">Sort A-Z</li>\r\n");
      out.write("                                <li class=\"list-group-item\" id=\"sort-desc\">Sort Z-A</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-9\">\r\n");
      out.write("                    \r\n");
      out.write("                            <div class=\"row\" id=\"cardContainer\">\r\n");
      out.write("                                <!-- Card 1 -->\r\n");
      out.write("                                <div class=\"col-md-4 col-12 card-item\">\r\n");
      out.write("                                    <div class=\"card\" style=\"cursor: pointer;\" data-bs-toggle=\"modal\" data-bs-target=\"#card1Modal\">\r\n");
      out.write("                                        <img src=\"https://ytesaigon.com/wp-content/uploads/2023/02/May-do-duong-huyet-On-Call-EZ-II.jpg.webp\" class=\"card-img-top\" alt=\"Card 1\">\r\n");
      out.write("                                        <div class=\"card-body\">\r\n");
      out.write("                                            <h5 class=\"card-title\">Máy đo đường huyết</h5>\r\n");
      out.write("                                            <p class=\"card-text\">Click xem thông tin chi tiết</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Card 2 -->\r\n");
      out.write("                                <div class=\"col-md-4 col-12 card-item\">\r\n");
      out.write("                                    <div class=\"card\" style=\"cursor: pointer;\" data-bs-toggle=\"modal\" data-bs-target=\"#card2Modal\">\r\n");
      out.write("                                        <img src=\"https://cdn.tgdd.vn/Products/Images/5872/283254/khau-trang-y-te-mask-care-4-lop-trang-hop-50-cai-thumb-1-600x600.jpg\" class=\"card-img-top\" alt=\"Card 2\">\r\n");
      out.write("                                        <div class=\"card-body\">\r\n");
      out.write("                                            <h5 class=\"card-title\">Khẩu trang y tế 4 lớp</h5>\r\n");
      out.write("                                            <p class=\"card-text\">Click xem thông tin chi tiết</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Card 3 -->\r\n");
      out.write("                                <div class=\"col-md-4 col-12 card-item\">\r\n");
      out.write("                                    <div class=\"card\" style=\"cursor: pointer;\" data-bs-toggle=\"modal\" data-bs-target=\"#card3Modal\">\r\n");
      out.write("                                        <img src=\"https://cdn.nhathuoclongchau.com.vn/unsafe/https://cms-prod.s3-sgn09.fptcloud.com/00017885_bong_gac_dap_vet_thuong_bao_thach_8cm_x_12cm_2863_62ae_large_ca54514759.jpg\" class=\"card-img-top\" alt=\"Card 3\">\r\n");
      out.write("                                        <div class=\"card-body\">\r\n");
      out.write("                                            <h5 class=\"card-title\">Bông gạc y tế</h5>\r\n");
      out.write("                                            <p class=\"card-text\">Click xem thông tin chi tiết</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            \r\n");
      out.write("                <!-- Modal for Card 1 -->\r\n");
      out.write("                <div class=\"modal fade\" id=\"card1Modal\" tabindex=\"-1\" aria-labelledby=\"card1ModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("                    <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("                        <div class=\"modal-content\">\r\n");
      out.write("                            <div class=\"modal-header\">\r\n");
      out.write("                                <h5 class=\"modal-title\" id=\"card1ModalLabel\">Mô tả Sản phẩm</h5>\r\n");
      out.write("                                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"modal-body\">\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\" col-12 col-md-6\">\r\n");
      out.write("                                        <label for=\"material_name\" class=\"form-label\">Tên sản phẩm</label>\r\n");
      out.write("                                        <input id=\"material_name\" name=\"material_name\" type=\"text\" class=\"form-control\" value=\"Máy đo đường huyết On Call EZ II\" readonly>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"col-12 col-md-6\">\r\n");
      out.write("                                        <label for=\"material_country\" class=\"form-label\">Quốc gia sản xuất</label>\r\n");
      out.write("                                        <input id=\"material_country\" name=\"material_country\" type=\"text\" class=\"form-control\" value=\"Mỹ\" readonly>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <label for=\"material_describe\" class=\"form-label\">Mô tả</label>\r\n");
      out.write("                                <textarea name=\"material_describe\" id=\"material_describe\" class=\"form-control\" rows=\"4\" readonly> Máy đo đường huyết On Call EZ II được sản xuất bởi tập đoàn ACON Laboratories Inc., USA dựa trên công nghệ mới với chất lượng rất cao, cách sử dụng đơn giản, tiện lợi và kết quả đo chính xác. Đặc biệt nguồn cung cấp que  thử dồi dào với giá cả rất hợp lý đã đáp ứng được nguyện vọng của đông đảo bệnh nhân tiểu đường trên toàn thế giới. Máy được sử dụng rộng rãi tại các bệnh viện, trung tâm y tế, phòng mạch cũng như tại gia đình.\r\n");
      out.write("                                </textarea>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\"col-12 col-md-4\">\r\n");
      out.write("                                        <label for=\"material_unit\" class=\"form-label\">Đơn vị</label>\r\n");
      out.write("                                        <input id=\"material_unit\" name=\"material_unit\" class=\"form-control\" type=\"text\" value=\"Chiếc\" readonly>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"col-12 col-md-4\">\r\n");
      out.write("                                        <label for=\"material_date\" class=\"form-label\">Ngày sản xuất</label>\r\n");
      out.write("                                        <input id=\"material_date\" name=\"material_date\" class=\"form-control\" type=\"text\" value=\"03-04-2017\" readonly>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"col-12 col-md-4\">\r\n");
      out.write("                                        <label for=\"material_expiry\" class=\"form-label\">Hạn sử dụng</label>\r\n");
      out.write("                                        <input id=\"material_expiry\" name=\"material_expiry\" class=\"form-control\" type=\"text\" value=\"Đến khi hỏng\" readonly>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <label for=\"material_use\" class=\"form-label\">Cách sử dụng</label>\r\n");
      out.write("                                <textarea name=\"material_use\" id=\"material_use\" rows=\"4\" class=\"form-control\" readonly> Chuẩn bị các dụng cụ đo. Lắp kim mới vào bút lấy máu. Chuẩn bị một que đo mới. Chuẩn bị một miếng cồn để sát khuẩn. Rửa tay bằng xà phòng và lau khô. Sát khuẩn vị trí lấy máu (đầu ngón tay) bằng cồn và chờ cho cồn bay hơi hết (đầu ngón tay khô). Gắn que đo vào máy, máy sẽ tự động bật lên. Chờ cho đến khi trên màn hình xuất hiện biểu tượng giọt máu. Sau khi điều chỉnh độ nông sâu phù hợp áp đầu bút lấy máu vào ngón tay để chích máu. Mẹo để lấy máu ít đau là bạn nên chích kim ở bên cạnh đầu ngón tay. Không nên chích ở giữa vì ở giữa là nơi tập trung nhiều dây thần kinh do vậy bạn sẽ cảm thấy đau nhiều hơn. Thấm máu vào que đo. Lưu ý bạn cần cung cấm lượng máu đủ để đo. Trong trường hợp thiếu máu máy sẽ báo lỗi và que đo đó sẽ không được sử dụng lại. Máy sẽ bắt đầu đếm ngược và sau 10s kết quả sẽ hiện trên màn hình.\r\n");
      out.write("                                </textarea>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\"col-12 col-md-6\">\r\n");
      out.write("                                        <label for=\"material_supplier\" class=\"form-label\">Nhà cung cấp</label>\r\n");
      out.write("                                        <textarea name=\"material_supplier\" id=\"material_supplier\" class=\"form-control\" readonly>ArtCare Medical - Công Ty Cổ Phần Thương Mại Và Dịch Vụ ArtCare</textarea>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"col-12 col-md-6\">\r\n");
      out.write("                                        <label for=\"material_value\" class=\"form-label\">Giá tiền</label>\r\n");
      out.write("                                        <input type=\"text\" name=\"material_value\" id=\"material_value\" class=\"form-control\" value=\"499.00\" readonly>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                                             \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("    </main>\r\n");
      out.write("    <!--end main content-->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/vattu_user.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
