/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.88
 * Generated at: 2024-11-26 07:58:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.html;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class yeucau_005fuser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar", Long.valueOf(1732605426315L));
    _jspx_dependants.put("jar:file:/D:/Documents/JAVAWEB/QLVT/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/quanlivattu/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar!/META-INF/c.tld", Long.valueOf(1323233178000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Yêu cầu vật tư</title>\r\n");
      out.write("    <!--css-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/yeucau_user.css\">\r\n");
      out.write("    <!--boostrap-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bootstrap/bootstrap.min.css\">\r\n");
      out.write("    <!--icon-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/icon/font/bootstrap-icons.min.css\">\r\n");
      out.write("    <!--js bootstrap-->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bootstrap/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <!--font-->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400..700&family=Mona+Sans:ital,wght@0,200..900;1,200..900&family=Noto+Sans:ital,wght@0,100..900;1,100..900&family=Playfair+Display:ital,wght@0,400..900;1,400..900&family=Playwrite+DE+Grund:wght@100..400&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"font-family: 'Mona Sans', serif;\">\r\n");
      out.write("    <!--sidebar-->\r\n");
      out.write("    <div id=\"sidebar\" class=\"sidebar\">\r\n");
      out.write("        <div class=\"m-3 mt-3\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"logo d-flex align-items-center\">\r\n");
      out.write("                <a class=\"nav-link fade-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/html/trangchu_user.jsp\">\r\n");
      out.write("                    <i class=\"bi bi-heart-pulse-fill\"></i>\r\n");
      out.write("                    <span class=\"ms-2\">VẬT TƯ Y TẾ</span>\r\n");
      out.write("                </a>               \r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"dashboard mt-5 ms-3\">\r\n");
      out.write("            <ul class=\"navbar-nav\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link ms-3 m-2 fade-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/html/vattu_user.jsp\">\r\n");
      out.write("                        <i class=\"bi bi-database-fill me-2\"></i>\r\n");
      out.write("                        Vật tư & thiết bị\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li  id=\"checked\" class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link ms-3 m-2 fade-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/html/yeucau_user.jsp\">\r\n");
      out.write("                        <i class=\"bi bi-hand-index-fill me-2\"></i>\r\n");
      out.write("                        Yêu cầu vật tư\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link ms-3 m-2 fade-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/html/lichsu_user.jsp\">\r\n");
      out.write("                        <i class=\"bi bi-clock-history me-2\"></i>\r\n");
      out.write("                        Lịch sử yêu cầu\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link ms-3 m-2 fade-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/html/nhan_user.jsp\">\r\n");
      out.write("                        <i class=\"bi bi-inboxes-fill me-2\"></i>\r\n");
      out.write("                        Nhận vật tư\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"log-out\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/html/dangnhap.jsp\">\r\n");
      out.write("                Đăng Xuất\r\n");
      out.write("                <i class=\"bi bi-box-arrow-right\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("       \r\n");
      out.write("    </div>\r\n");
      out.write("    <!--end sidebar-->\r\n");
      out.write("    <!--main content-->\r\n");
      out.write("    <main id=\"main-content\" class=\"main-content\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"header\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row w-100\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"toggle col-1 col-sm-1\">\r\n");
      out.write("                    <button id=\"toggle\">☰</button>\r\n");
      out.write("                </div>\r\n");
      out.write("    \r\n");
      out.write("                <div class=\"search-bar col-11 col-sm-7\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" placeholder=\"Tìm kiếm gì đó...\">\r\n");
      out.write("                </div>\r\n");
      out.write("    \r\n");
      out.write("                <div class=\"hello col-12 col-sm-4\">\r\n");
      out.write("                    <span id=\"hello\">Xin chào!</span>\r\n");
      out.write("                    <span id=\"name\">Nguyễn Anh Đức</span>\r\n");
      out.write("                    <span><img src=\"https://png.pngtree.com/png-vector/20220429/ourlarge/pngtree-human-template-doctor-avatar-white-individual-vector-png-image_27845716.jpg\" alt=\"\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"content-here\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-title\">\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/image/icon-medical.avif\" alt=\"\">\r\n");
      out.write("                <div id=\"div1\">YÊU CẦU VẬT TƯ</div>\r\n");
      out.write("                <div id=\"div2\">Điền đầy đủ thông tin vào trường bên dưới để yêu cầu xin vật tư.</div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-content\">\r\n");
      out.write("                <div class=\"form-content-child\">\r\n");
      out.write("                    <form id=\"myForm\" action=\"#\" method=\"post\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-12 col-sm-6\">\r\n");
      out.write("                                <label for=\"email\" class=\"form-lable\">Email</label>\r\n");
      out.write("                                <input id=\"email\" name=\"email\" type=\"text\" class=\"form-control\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-12 col-sm-6\">\r\n");
      out.write("                                <label for=\"fullname\" class=\"form-lable\">Họ và tên</label>\r\n");
      out.write("                                <input id=\"fullname\" name=\"name\" type=\"name\" class=\"form-control\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-12 col-sm-6\">\r\n");
      out.write("                                <label for=\"phonenumber\" class=\"form-lable\">Số điện thoại</label>\r\n");
      out.write("                                <input id=\"phonenumber\" name=\"phonenumber\" type=\"number\" class=\"form-control\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-12 col-sm-6\">\r\n");
      out.write("                                <label for=\"daterq\" class=\"form-lable\">Ngày yêu cầu</label>\r\n");
      out.write("                                <input id=\"daterq\" name=\"date-rq\" type=\"date\" class=\"form-control\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-12 col-sm-6\">\r\n");
      out.write("                                <label for=\"materialname\" class=\"form-lable\">Tên vật tư</label>\r\n");
      out.write("                                <input id=\"materialname\" name=\"materialname\" type=\"text\" class=\"form-control\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-12 col-sm-6\">\r\n");
      out.write("                                <label for=\"quantity\" class=\"form-lable\">Số lượng</label>\r\n");
      out.write("                                <input id=\"quantity\" name=\"quantity\" type=\"number\" class=\"form-control\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <label for=\"reason\" class=\"form-lable\">Lý do</label> <br>\r\n");
      out.write("                            <textarea class=\"form-control\" name=\"reason\" id=\"reason\" rows=\"4\" cols=\"91\" required></textarea>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <label for=\"note\" class=\"form-lable\">Ghi chú</label>\r\n");
      out.write("                            <textarea class=\"form-control\" name=\"reason\" id=\"reason\" rows=\"2\" cols=\"91\"></textarea>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"btn-submit\">\r\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-primary\">Gửi yêu cầu</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </main>\r\n");
      out.write("    <!--end main content-->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/vattu_user.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
